### ISSUE TITLE
Windows 7 64位系统下，打包失败 

### ISSUE THREAD

**Issue by geekxiaoke** [geeeeeeeeek/electronic-wechat#118]
在Windows 7 64位系统下，使用打包命令 npm run build:win 打包失败，正常使用倒是没问题，日志如下：
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:win' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'prebuild:win', 'build:win', 'postbuild:win' ]
5 info prebuild:win electronic-wechat@1.1.1
6 info build:win electronic-wechat@1.1.1
7 verbose unsafe-perm in lifecycle true
8 info electronic-wechat@1.1.1 Failed to exec build:win script
9 verbose stack Error: electronic-wechat@1.1.1 build:win: `./scripts/build.sh win32 ia32`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid electronic-wechat@1.1.1
11 verbose cwd C:\Program Files (x86)\Tencent\electronic-wechat
12 error Windows_NT 6.1.7601
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:win"
14 error node v4.4.2
15 error npm  v2.15.0
16 error code ELIFECYCLE
17 error electronic-wechat@1.1.1 build:win: `./scripts/build.sh win32 ia32`
17 error Exit status 1
18 error Failed at the electronic-wechat@1.1.1 build:win script './scripts/build.sh win32 ia32'.
18 error This is most likely a problem with the electronic-wechat package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     ./scripts/build.sh win32 ia32
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs electronic-wechat
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls electronic-wechat
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by geeeeeeeeek** [comment]
@geekxiaoke Windows平台我就不管了…有兴趣维护可以发下PR…
