### ISSUE TITLE
ubuntukylin 安装，启动报如下错误，不能启动

### ISSUE THREAD

**Issue by vinartis** [geeeeeeeeek/electronic-wechat#149]
> electronic-wechat@1.2.0 start /home/leonis/source/electronic-wechat
> electron src/main.js

No protocol specified
```
npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@1.2.0 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-wechat@1.2.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/leonis/source/electronic-wechat/npm-debug.log


0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.8.3
3 info using node@v5.10.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electronic-wechat@1.2.0~prestart: electronic-wechat@1.2.0
6 silly lifecycle electronic-wechat@1.2.0~prestart: no script for prestart, continuing
7 info lifecycle electronic-wechat@1.2.0~start: electronic-wechat@1.2.0
8 verbose lifecycle electronic-wechat@1.2.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle electronic-wechat@1.2.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/leonis/source/electronic-wechat/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle electronic-wechat@1.2.0~start: CWD: /home/leonis/source/electronic-wechat
11 silly lifecycle electronic-wechat@1.2.0~start: Args: [ '-c', 'electron src/main.js' ]
12 silly lifecycle electronic-wechat@1.2.0~start: Returned: code: 1  signal: null
13 info lifecycle electronic-wechat@1.2.0~start: Failed to exec start script
14 verbose stack Error: electronic-wechat@1.2.0 start: `electron src/main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid electronic-wechat@1.2.0
16 verbose cwd /home/leonis/source/electronic-wechat
17 error Linux 4.4.0-21-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.10.1
20 error npm  v3.8.3
21 error code ELIFECYCLE
22 error electronic-wechat@1.2.0 start: `electron src/main.js`
22 error Exit status 1
23 error Failed at the electronic-wechat@1.2.0 start script 'electron src/main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electronic-wechat package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron src/main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electronic-wechat
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electronic-wechat
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by geeeeeeeeek** [comment]
@vinartis 确保你的electron版本是最新v0.37.6，有API改动。
