### ISSUE TITLE
cannot run the project

### ISSUE THREAD

**Issue by jyanchen** [geeeeeeeeek/electronic-wechat#152]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.36.9`
- Version of Node.js (run `$ node --version`): `v5.10.1`
- OS: `linux mint 17`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/***/electronic-wechat/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/home/jyan/Work/git/electronic-wechat/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)

```

**Comment by geeeeeeeeek** [comment]
Refer to #153. Update you electron.
