### ISSUE TITLE
v1.3.0 Release Notes

### ISSUE THREAD

**Issue by geeeeeeeeek** [geeeeeeeeek/electronic-wechat#202]
这个版本主要是基础体验的优化以及代码重构、bug 修复。

值得庆祝的是，electron 在长达近三年的开发后终于发布了正式版 v1.x。在这个 release 中，我们也将项目依赖的 electron 版本升级到了最新的 v1.1.0 ， Chrome 和 Node 版本也分别升级到了 50.0 和 6.1。我们可以享受到更好的性能及 ES 6 等特性的支持。**由于 electron 的 API 变动，这次更新后使用旧版本的 electron 将无法启动应用，请使用 `npm install` 升级你的 electron 版本。**

另外，设置面板已加入 v2.x 的开发计划，@lfs1102 正在准备中。完成之后，通知隐藏消息内容、Flash支持、快捷键、托盘图标逻辑等功能可以优雅地加入。

**v1.3 (2016.05.19)**

1. 升级 electron 至 1.1.0， Chrome 至 50.0.2661.102，Node 至 6.1.0 (感谢 @lfs1102 的贡献)
2. 新增 `brew cask` 安装方式 (最新可下载版本为 v1.2.0)
3. 新增 Windows 下的安装脚本 (感谢 @3dseals 的贡献)
4. 新增 应用启动动画，缩短首次展现时间
5. 优化 应用启动稳定性，增加超时重试
6. 优化 主要文案均统一为英文
7. 优化 减少 20M 应用体积
8. 修复 关于页面版本号显示的 bug
9. 修复 Linux 系统下左边栏组件重叠的 bug
10. 修复 部分 Linux KDE 系统下托盘图标空白的 bug
11. 其他修改 (感谢 @wzyboy, @rivershang, @hexchain, @samurai00, @boltomli 的贡献)

**Comment by anota** [comment]
一直starting app是什么情况呢？

**Comment by geeeeeeeeek** [comment]
@anota #224 OS X 兼容性问题

**Comment by cancelpj** [comment]
是否不能再windows操作系统下运行，一直starting app

**Comment by i2000s** [comment]
Ubuntu 16.04下怎么安装？

```
$ sudo npm install && sudo npm start

> nodejieba@2.2.2 install /media/E/SoftwareRep/GitHub/electronic-wechat/node_modules/nodejieba
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.6.4-040604-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /media/E/SoftwareRep/GitHub/electronic-wechat/node_modules/nodejieba
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:nodejieba@2.2.2 nodejieba@2.2.2 install: `node-gyp rebuild`
npm WARN install:nodejieba@2.2.2 Exit status 1

> electron-prebuilt@1.3.0 postinstall /media/E/SoftwareRep/GitHub/electronic-wechat/node_modules/electron-prebuilt
> node install.js

sh: 1: node: not found
npm ERR! Linux 4.6.4-040604-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! electron-prebuilt@1.3.0 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electron-prebuilt@1.3.0 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/E/SoftwareRep/GitHub/electronic-wechat/npm-debug.log
```
我使用了npm, 结果
```
$ sudo npm install electron
npm WARN deprecated electron@0.4.1: The original electron project has been moved. Visit github.com/logicalparadox/electron for more details.

> nodejieba@2.2.2 install /media/E/SoftwareRep/GitHub/electronic-wechat/node_modules/nodejieba
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.6.4-040604-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /media/E/SoftwareRep/GitHub/electronic-wechat/node_modules/nodejieba
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:nodejieba@2.2.2 nodejieba@2.2.2 install: `node-gyp rebuild`
npm WARN install:nodejieba@2.2.2 Exit status 1
electronic-wechat@1.3.0 /media/E/SoftwareRep/GitHub/electronic-wechat
└── electron@0.4.1  extraneous
```

**Comment by bash-horatio** [comment]
@i2000s node和nodejs一个东西，安装nodejs-legacy就行
