### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by iVanlIsh** [geeeeeeeeek/electronic-wechat#203]
#### Description
敲npm start然后跳出一个窗口 显示A JavaScript error occurred in the main process
下面是细节
```
Uncaught Exception:
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/opt/homebrew-cask/Caskroom/electron/0.36.0/Electron.app/Contents/Resources/default_app/main.js:252:23)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.36.0`
- OS: `<10.11.4>`
- Stack trace from the error message (if any)
下面是shell里的提示
``` 
> electronic-wechat@1.3.0 start /Users/ivan_l/GitHub/electronic-wechat
> electron src/main.js

App threw an error when running [SyntaxError: Unexpected token {]
```

**Comment by geeeeeeeeek** [comment]
检查 npm install。
