### ISSUE TITLE
OS X: 手动build出的应用无法启动

### ISSUE THREAD

**Issue by yPangXie** [geeeeeeeeek/electronic-wechat#209]
#### Description

本地打包`npm run build:osx`, 应用目录下的app打开报错

<img width="532" alt="2016-05-21 11 24 21" src="https://cloud.githubusercontent.com/assets/12368943/15449260/27379734-1fab-11e6-97f0-b4e3b5241b81.png">

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.1.0`
- OS: `OS X 10.11.4 (15E65)`
- Stack trace from the error message (if any) NO

**Comment by ray26** [comment]
你试试npm install && npm start 来看看能不能启动

**Comment by yPangXie** [comment]
也还是不行. 报了另外一个错误

```javascript
> electronic-wechat@1.3.0 start /xxx/electronic-wechat
> electron src/main.js

fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/xxx/electronic-wechat/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.<anonymous> (/xxx/electronic-wechat/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

```

**Comment by geeeeeeeeek** [comment]
@yPangXie node module 安装的问题。删除后重装即可。

**Comment by yPangXie** [comment]
重装成功, `npm start` 可以正常启动. 但是执行`npm run build:osx`打包之后, `Applications`目录下的应用打开依旧是截图的问题.

**Comment by geeeeeeeeek** [comment]
@yPangXie 删除`Applications`下的应用重试

**Comment by yPangXie** [comment]
还是不行~

**Comment by geeeeeeeeek** [comment]
@yPangXie 你这bug不按基本法啊…

**Comment by yPangXie** [comment]
@geeeeeeeeek 我心里也特别苦啊 😂
