### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by OscarGong** [geeeeeeeeek/electronic-wechat#22]
## Terminal :
```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@0.1.0 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-wechat@0.1.0 start script 'electron src/main.js'.
npm ERR! This is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
```

## Log: 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.14.12
3 info using node@v4.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart electronic-wechat@0.1.0
6 info start electronic-wechat@0.1.0
7 verbose unsafe-perm in lifecycle true
8 info electronic-wechat@0.1.0 Failed to exec start script
9 verbose stack Error: electronic-wechat@0.1.0 start: `electron src/main.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:821:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid electronic-wechat@0.1.0
11 verbose cwd /Users/Oscar/electronic-wechat
12 error Darwin 15.3.0
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
14 error node v4.3.1
15 error npm  v2.14.12
16 error code ELIFECYCLE
17 error electronic-wechat@0.1.0 start: `electron src/main.js`
17 error Exit status 1
18 error Failed at the electronic-wechat@0.1.0 start script 'electron src/main.js'.
18 error This is most likely a problem with the electronic-wechat package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron src/main.js
18 error You can get their info via:
18 error     npm owner ls electronic-wechat
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by geeeeeeeeek** [comment]
Looks like your `npm start` failed rather than `npm build`. First you need to check if `electron` is installed via `electron -v`. An easy way to install it is running `npm install` in that folder.

If it's not the case, more information is needed to diagnose what is going wrong.
