### ISSUE TITLE
用最新源码编译后启动失败

### ISSUE THREAD

**Issue by zaobao** [geeeeeeeeek/electronic-wechat#289]
#### Description
用最新源码编译后启动失败

#### Specifications

- Version of Electron (run `$ electron --version`): npm自动装的
- OS: `Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux`
- Stack trace from the error message (if any)

``` 
mczhao:electronic-wechat$ npm install
mczhao:electronic-wechat$ npm start

> electronic-wechat@1.3.0 start /home/mczhao/Applications/electronic-wechat
> electron src/main.js

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/mczhao/Applications/electronic-wechat/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.<anonymous> (/home/mczhao/Applications/electronic-wechat/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@1.3.0 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-wechat@1.3.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/mczhao/Applications/electronic-wechat/npm-debug.log

```

**Comment by cyio** [comment]
[Oaker's Blog - npm遇安装故障往往是墙的锅](http://cyio.coding.me/?p=69&t=1469022943328)

**Comment by geeeeeeeeek** [comment]
网络问题就不管了

**Comment by vipzrx** [comment]
我在安装的过程中，遇到了和你一样的问题@cyio . 我使用的是ss翻墙，使用代理127.0.0.1:8080 墙问该怎么写命令行

**Comment by cyio** [comment]
@vipzrx 

`proxychains npm install` 这个命令就是解决方法，你没配置proxychains?

安装：`sudo apt install proxychains`
配置路径：`~/.proxychains/proxychains.conf`
我的配置，socks5那行一般要改
```bash
strict_chain
proxy_dns 
remote_dns_subnet 224
tcp_read_time_out 15000
tcp_connect_time_out 8000
localnet 127.0.0.0/255.0.0.0
quiet_mode

[ProxyList]
socks5  127.0.0.1 1080
```

**Comment by linux0ne** [comment]
@vipzrx 
SS翻墙——这是什么软件？
