### ISSUE TITLE
扫码后报JS的错误

### ISSUE THREAD

**Issue by toddleo** [geeeeeeeeek/electronic-wechat#346]
#### Description

扫码后弹出alert:

```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: app.setBadgeCount is not a function
    at EventEmitter.ipcMain.on (/opt/arch/usr/share/electronic-wechat/src/main.js:52:15)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/api/web-contents.js:128:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

不停点OK但是不停弹
#### Specifications
- Version of Electron (run `$ electron --version`): `v0.37.5`
- OS: `Fedora 24`
- Stack trace from the error message (if any)

```
Uncaught Exception:
TypeError: app.setBadgeCount is not a function
    at EventEmitter.ipcMain.on (/opt/arch/usr/share/electronic-wechat/src/main.js:52:15)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
    at EventEmitter.<anonymous> (/usr/lib64/electron/resources/electron.asar/browser/api/web-contents.js:128:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

**Comment by ZiangYan** [comment]
较老的某次commit使用正常，git pull后出现了相同的错误。将整个目录删掉，重新git clone，重新npm install后问题解决。猜测是较老的commit中build后的东西和最新的代码不兼容导致的。

**Comment by toddleo** [comment]
现在没有再出现这个问题了.
