### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by kk17** [geeeeeeeeek/electronic-wechat#37]
Mac OS X EI Capitan node 5.0.0 运行`npm install`出现以下错误：
``` 
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! electron-prebuilt@0.36.9 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-prebuilt@0.36.9 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the electron-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls electron-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kk/Documents/reposities/electronic-wechat/npm-debug.log
```

**Comment by arrowrowe** [comment]
方便贴一下末行提到的 `npm-debug.log` 么?

**Comment by geeeeeeeeek** [comment]
This is most likely a problem with the electron-prebuilt package.

上游electron安装的问题，你去它的项目里报issue。。

**Comment by kk17** [comment]
```
14346 silly lifecycle electron-packager@5.2.1~postinstall: no script for postinstall, continuing
14347 silly postinstall electron-prebuilt@0.36.9 /Users/kk/Documents/reposities/electronic-wechat/node_modules/.staging/electron-prebuilt-a3147d7a7cbe0f9d6e088c15b244d45c
14348 info lifecycle electron-prebuilt@0.36.9~postinstall: electron-prebuilt@0.36.9
14349 verbose lifecycle electron-prebuilt@0.36.9~postinstall: unsafe-perm in lifecycle true
14350 verbose lifecycle electron-prebuilt@0.36.9~postinstall: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/kk/Documents/reposities/electronic-wechat/node_modules/electron-prebuilt/node_modules/.bin:/Users/kk/Documents/reposities/electronic-wechat/node_modules/.bin:/usr/local/var/rbenv/shims:/usr/local/opt/jenv/shims:/usr/local/var/pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/kk/scripts:/Users/kk/usefull-bash-scripts:/Users/kk/usefull-python-scripts:/Users/kk/Documents/go-workspace/bin
14351 verbose lifecycle electron-prebuilt@0.36.9~postinstall: CWD: /Users/kk/Documents/reposities/electronic-wechat/node_modules/electron-prebuilt
14352 silly lifecycle electron-prebuilt@0.36.9~postinstall: Args: [ '-c', 'node install.js' ]
14353 silly lifecycle electron-prebuilt@0.36.9~postinstall: Returned: code: 1  signal: null
14354 info lifecycle electron-prebuilt@0.36.9~postinstall: Failed to exec postinstall script
14355 verbose unlock done using /Users/kk/.npm/_locks/staging-49fa4ced3b9b27aa.lock for /Users/kk/Documents/reposities/electronic-wechat/node_modules/.staging
14356 silly rollbackFailedOptional Starting
14357 silly rollbackFailedOptional Finishing
14358 silly runTopLevelLifecycles Starting
14359 silly runTopLevelLifecycles Finishing
14360 silly install printInstalled
14361 verbose stack Error: electron-prebuilt@0.36.9 postinstall: `node install.js`
14361 verbose stack Exit status 1
14361 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
14361 verbose stack     at emitTwo (events.js:87:13)
14361 verbose stack     at EventEmitter.emit (events.js:172:7)
14361 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14361 verbose stack     at emitTwo (events.js:87:13)
14361 verbose stack     at ChildProcess.emit (events.js:172:7)
14361 verbose stack     at maybeClose (internal/child_process.js:818:16)
14361 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14362 verbose pkgid electron-prebuilt@0.36.9
14363 verbose cwd /Users/kk/Documents/reposities/electronic-wechat
14364 error Darwin 15.3.0
14365 error argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install"
14366 error node v5.0.0
14367 error npm  v3.3.9
14368 error code ELIFECYCLE
14369 error electron-prebuilt@0.36.9 postinstall: `node install.js`
14369 error Exit status 1
14370 error Failed at the electron-prebuilt@0.36.9 postinstall script 'node install.js'.
14370 error This is most likely a problem with the electron-prebuilt package,
14370 error not with npm itself.
14370 error Tell the author that this fails on your system:
14370 error     node install.js
14370 error You can get their info via:
14370 error     npm owner ls electron-prebuilt
14370 error There is likely additional logging output above.
14371 verbose exit [ 1, true ]
```

**Comment by ericjee** [comment]
rm -rf ~/.electron/
npm cache clear
npm install

去他们issue里面搜的，this work for me

**Comment by chaegumi** [comment]
@ericjee work for me too
