### ISSUE TITLE
Arch linux can not use the git to build app

### ISSUE THREAD

**Issue by rainplus** [geeeeeeeeek/electronic-wechat#381]
#### Description

i clone this repo.and do the scritp "npm install && and start" but is failed>

#### Specifications
[anonymous@rainpluss-archlinux electronic-wechat]$ npm run build:linux && npm start

> electronic-wechat@1.4.0 build:linux /home/anonymous/Gits/electronic-wechat
> ./scripts/build.sh linux x64

\033[0;31mError\033[0m: you need to npm install electron-packager. Aborting.

npm ERR! Linux 4.8.7-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build:linux"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@1.4.0 build:linux: `./scripts/build.sh linux x64`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-wechat@1.4.0 build:linux script './scripts/build.sh linux x64'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/build.sh linux x64
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anonymous/Gits/electronic-wechat/npm-debug.log

```/home/anonymous/Gits/electronic-wechat/npm-debug.log ```

``` 
[anonymous@rainpluss-archlinux electronic-wechat]$ cat /home/anonymous/Gits/electronic-wechat/npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build:linux' ]
2 info using npm@3.10.9
3 info using node@v7.1.0
4 verbose run-script [ 'prebuild:linux', 'build:linux', 'postbuild:linux' ]
5 info lifecycle electronic-wechat@1.4.0~prebuild:linux: electronic-wechat@1.4.0
6 silly lifecycle electronic-wechat@1.4.0~prebuild:linux: no script for prebuild:linux, continuing
7 info lifecycle electronic-wechat@1.4.0~build:linux: electronic-wechat@1.4.0
8 verbose lifecycle electronic-wechat@1.4.0~build:linux: unsafe-perm in lifecycle true
9 verbose lifecycle electronic-wechat@1.4.0~build:linux: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/anonymous/Gits/electronic-wechat/node_modules/.bin:/usr/local/bin:/usr/local/sbin:/usr/bin
10 verbose lifecycle electronic-wechat@1.4.0~build:linux: CWD: /home/anonymous/Gits/electronic-wechat
11 silly lifecycle electronic-wechat@1.4.0~build:linux: Args: [ '-c', './scripts/build.sh linux x64' ]
12 silly lifecycle electronic-wechat@1.4.0~build:linux: Returned: code: 1  signal: null
13 info lifecycle electronic-wechat@1.4.0~build:linux: Failed to exec build:linux script
14 verbose stack Error: electronic-wechat@1.4.0 build:linux: `./scripts/build.sh linux x64`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electronic-wechat@1.4.0
16 verbose cwd /home/anonymous/Gits/electronic-wechat
17 error Linux 4.8.7-1-ARCH
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build:linux"
19 error node v7.1.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error electronic-wechat@1.4.0 build:linux: `./scripts/build.sh linux x64`
22 error Exit status 1
23 error Failed at the electronic-wechat@1.4.0 build:linux script './scripts/build.sh linux x64'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electronic-wechat package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ./scripts/build.sh linux x64
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electronic-wechat
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electronic-wechat
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by Kulbear** [comment]
you need to npm install electron-packager. Aborting.

**Comment by rainplus** [comment]
3Q
