### ISSUE TITLE
npm install报错

### ISSUE THREAD

**Issue by BlackHole1** [geeeeeeeeek/electronic-wechat#403]
是内核问题么？我的内核是最新的4.9版本。node版本我换了6.2x和4.4.4都不行，依旧是下面的错
```
npm ERR! Linux 4.9.0-040900-generic
npm ERR! argv "/home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/bin/node" "/home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint-plugin-jsx-a11y@3.0.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@13.0.0 wants eslint-plugin-jsx-a11y@^2.2.3

npm ERR! Please include the following file with any support request:
npm ERR!     /home/black-hole/Black-Hole/other/electronic-wechat/npm-debug.log
```

npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/bin/node',
1 verbose cli   '/home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/bin/npm',
1 verbose cli   'install' ]
2 info using npm@2.15.1
3 info using node@v4.4.4
4 verbose readDependencies loading dependencies from /home/black-hole/Black-Hole/other/electronic-wechat/package.json
5 verbose install where, deps [ '/home/black-hole/Black-Hole/other/electronic-wechat',
5 verbose install   [ 'electron',
5 verbose install     'electron-packager',
5 verbose install     'nconf',
5 verbose install     'pinyin',
5 verbose install     'babel-eslint',
5 verbose install     'eslint',
5 verbose install     'eslint-config-airbnb',
5 verbose install     'eslint-plugin-import',
5 verbose install     'eslint-plugin-jsx-a11y',
5 verbose install     'eslint-plugin-react' ] ]
6 verbose install where, peers [ '/home/black-hole/Black-Hole/other/electronic-wechat', [] ]
7 verbose installManyTop reading for lifecycle /home/black-hole/Black-Hole/other/electronic-wechat/package.json
8 info preinstall electronic-wechat@1.4.0
9 verbose installManyTop reading scoped package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/babel-eslint/package.json
10 verbose installManyTop reading scoped package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/electron/package.json
11 verbose installManyTop reading scoped package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/electron-packager/package.json
12 verbose installManyTop reading scoped package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/eslint/package.json
13 verbose installManyTop reading scoped package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/eslint-config-airbnb/package.json
14 verbose installManyTop reading scoped package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/eslint-plugin-import/package.json
15 verbose installManyTop reading scoped package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/eslint-plugin-jsx-a11y/package.json
16 verbose installManyTop reading scoped package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/eslint-plugin-react/package.json
17 verbose installManyTop reading scoped package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/nconf/package.json
18 verbose installManyTop reading scoped package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/pinyin/package.json
19 verbose readDependencies loading dependencies from /home/black-hole/Black-Hole/other/electronic-wechat/package.json
20 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/babel-eslint/package.json
21 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/electron/package.json
22 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/electron-packager/package.json
23 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/eslint/package.json
24 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/eslint-config-airbnb/package.json
25 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/eslint-plugin-import/package.json
26 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/eslint-plugin-jsx-a11y/package.json
27 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/eslint-plugin-react/package.json
28 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/nconf/package.json
29 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/pinyin/package.json
30 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/.bin/electron/package.json
31 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/.bin/electron-packager/package.json
32 verbose targetResolver reading package data from /home/black-hole/Black-Hole/other/electronic-wechat/node_modules/.bin/eslint/package.json
33 verbose already installed skipping electron@^1.4.6 /home/black-hole/Black-Hole/other/electronic-wechat
34 verbose already installed skipping electron-packager@^8.2.0 /home/black-hole/Black-Hole/other/electronic-wechat
35 verbose already installed skipping nconf@^0.8.4 /home/black-hole/Black-Hole/other/electronic-wechat
36 verbose already installed skipping pinyin@^2.7.1 /home/black-hole/Black-Hole/other/electronic-wechat
37 verbose already installed skipping babel-eslint@^7.1.0 /home/black-hole/Black-Hole/other/electronic-wechat
38 verbose already installed skipping eslint@^3.4.0 /home/black-hole/Black-Hole/other/electronic-wechat
39 verbose already installed skipping eslint-config-airbnb@^13.0.0 /home/black-hole/Black-Hole/other/electronic-wechat
40 verbose already installed skipping eslint-plugin-import@^2.2.0 /home/black-hole/Black-Hole/other/electronic-wechat
41 verbose already installed skipping eslint-plugin-jsx-a11y@^3.0.1 /home/black-hole/Black-Hole/other/electronic-wechat
42 verbose already installed skipping eslint-plugin-react@^6.1.2 /home/black-hole/Black-Hole/other/electronic-wechat
43 silly install resolved []
44 info build /home/black-hole/Black-Hole/other/electronic-wechat
45 info linkStuff electronic-wechat@1.4.0
46 silly linkStuff electronic-wechat@1.4.0 has /home/black-hole/Black-Hole/other as its parent node_modules
47 verbose linkBins electronic-wechat@1.4.0
48 verbose linkMans electronic-wechat@1.4.0
49 verbose rebuildBundles electronic-wechat@1.4.0
50 verbose rebuildBundles [ '.bin',
50 verbose rebuildBundles   'babel-eslint',
50 verbose rebuildBundles   'electron',
50 verbose rebuildBundles   'electron-packager',
50 verbose rebuildBundles   'eslint',
50 verbose rebuildBundles   'eslint-config-airbnb',
50 verbose rebuildBundles   'eslint-plugin-import',
50 verbose rebuildBundles   'eslint-plugin-jsx-a11y',
50 verbose rebuildBundles   'eslint-plugin-react',
50 verbose rebuildBundles   'nconf',
50 verbose rebuildBundles   'pinyin' ]
51 info install electronic-wechat@1.4.0
52 info postinstall electronic-wechat@1.4.0
53 info prepublish electronic-wechat@1.4.0
54 verbose validateInstall loading /home/black-hole/Black-Hole/other/electronic-wechat/package.json for validation
55 verbose stack Error: The package eslint-plugin-jsx-a11y@3.0.2 does not satisfy its siblings' peerDependencies requirements!
55 verbose stack     at /home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/lib/node_modules/npm/lib/install.js:125:32
55 verbose stack     at /home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/lib/node_modules/npm/lib/install.js:268:7
55 verbose stack     at /home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/read-installed/read-installed.js:142:5
55 verbose stack     at /home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
55 verbose stack     at cb (/home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
55 verbose stack     at /home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
55 verbose stack     at cb (/home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
55 verbose stack     at /home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
55 verbose stack     at cb (/home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
55 verbose stack     at /home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/lib/node_modules/npm/node_modules/read-installed/read-installed.js:263:14
56 verbose cwd /home/black-hole/Black-Hole/other/electronic-wechat
57 error Linux 4.9.0-040900-generic
58 error argv "/home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/bin/node" "/home/black-hole/Black-Hole/env/nvm/versions/node/v4.4.4/bin/npm" "install"
59 error node v4.4.4
60 error npm  v2.15.1
61 error code EPEERINVALID
62 error peerinvalid The package eslint-plugin-jsx-a11y@3.0.2 does not satisfy its siblings' peerDependencies requirements!
62 error peerinvalid Peer eslint-config-airbnb@13.0.0 wants eslint-plugin-jsx-a11y@^2.2.3
63 verbose exit [ 1, true ]
```

**Comment by cacaxistudio** [comment]
碰到同样的问题，有谁知道怎么解决，NODE版本试过4，5，6，7

**Comment by BlackHole1** [comment]
你有升级内核么？好像是npm的问题，没有在看了，过年回去试一下

**Comment by cacaxistudio** [comment]
我装Mist的时候，也是卡在装Electronic上，难道是网络的问题？

**Comment by cacaxistudio** [comment]
你说的是kernel？ 我用的是4.6

**Comment by BlackHole1** [comment]
我之前换成了cnpm淘宝的源，但是还是不行。那就不是内核的问题

**Comment by cacaxistudio** [comment]
看来是个普遍的问题

**Comment by limz10** [comment]
same issue here

**Comment by VictorYu2015** [comment]
same issue

**Comment by wujysh** [comment]
see https://github.com/airbnb/javascript/issues/952
