### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by klj890** [geeeeeeeeek/electronic-wechat#469]
#### Description

我好像teach了一个空单json文件。。。然后就一直这样了

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `ubuntu`
- Stack trace from the error message (if any)

Uncaught Exception:
TypeError: Cannot read property 'setImage' of undefined
    at AppTray.setUnreadStat (/home/wangtao/electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/windows/controllers/app_tray.js:86:16)
    at EventEmitter.ipcMain.on (/home/wangtao/electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/main.js:53:21)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/home/wangtao/electronic-wechat/dist/electronic-wechat-linux-x64/resources/electron.asar/browser/api/web-contents.js:209:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)

```
<Stack trace here>
```

**Comment by Kulbear** [comment]
把那个删了就可以了 回自己重新生成的

**Comment by Huang-CL** [comment]
我也有类似的问题。
electron --version: v1.6.2
OS: ubuntu 14.04

把wechat的可执行文件做成桌面快捷方式之后，打开就会弹出一个对话框报这个错误

A JavaScript error occurred in the main process
Uncaught Exception:
Error: EIO: i/o error, write
    at Error (native)
    at Object.fs.writeSync (fs.js:786:20)
    at SyncWriteStream.write (fs.js:2230:6)
    at Console.warn (console.js:51:16)
    at checkAccelerator (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/node_modules/electron-localshortcut/index.js:107:11)
    at Object.register (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/node_modules/electron-localshortcut/index.js:55:2)
    at WeChatWindow.registerLocalShortcut (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/windows/controllers/wechat.js:160:27)
    at WeChatWindow.initWechatWindowShortcut (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/windows/controllers/wechat.js:170:10)
    at new WeChatWindow (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/windows/controllers/wechat.js:33:10)
    at ElectronicWeChat.createWeChatWindow (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/main.js:136:25)
可以点OK忽略之，然后就会一直卡在starting app的对话框上。

如果从命令行直接打开，会有如下错误
WARNING: CommandOrControl + H is not a valid accelerator.

    at WeChatWindow.initWechatWindowShortcut (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/windows/controllers/wechat.js:170:10)
    at new WeChatWindow (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/windows/controllers/wechat.js:33:10)
    at ElectronicWeChat.createWeChatWindow (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/main.js:136:25)
    at App.app.on (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/main.js:50:12)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)

Reconnect.

WARNING: CommandOrControl + H is not a valid accelerator.

    at BrowserWindow.wechatWindow.on (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/windows/controllers/wechat.js:155:12)
    at emitOne (events.js:101:20)
    at BrowserWindow.emit (events.js:188:7)
    at WeChatWindow.show (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/windows/controllers/wechat.js:76:23)
    at WeChatWindow.resizeWindow (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/windows/controllers/wechat.js:45:12)
    at EventEmitter.ipcMain.on (/.../electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/main.js:90:25)
    at emitTwo (events.js:106:13)

但是报完错之后，过一会微信就能正常使用

**Comment by Kulbear** [comment]
`WARNING: CommandOrControl + H is not a valid accelerator. `

这一句没关系 是一个使用的第三方库自己的问题 它无法判断组合

**Comment by mdj20130907** [comment]
去掉“electronic-wechat/src/windows/controllers/wechat.js”文件，去掉➕两侧的空格，'CommandOrControl+H'
