### ISSUE TITLE
安装依赖&运行应用出错

### ISSUE THREAD

**Issue by JoanYu** [geeeeeeeeek/electronic-wechat#476]
#### Description

如下

#### Specifications

- Version of Electron (run `$ electron --version`): `v1.4.15`
- OS: `Ubuntu 16.04 LTS`
- Stack trace from the error message (if any)
```
nodejieba@2.2.4 install /home/xduyzy/electronic-wechat/node_modules/nodejieba
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-59-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/xduyzy/electronic-wechat/node_modules/nodejieba
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:nodejieba@2.2.4 nodejieba@2.2.4 install: `node-gyp rebuild`
npm WARN install:nodejieba@2.2.4 Exit status 1

> electronic-wechat@2.0.0 start /home/xduyzy/electronic-wechat
> electron src/main.js

/usr/bin/env: "node": 没有那个文件或目录

npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electronic-wechat@2.0.0 start: `electron src/main.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electronic-wechat@2.0.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xduyzy/electronic-wechat/npm-debug.log
```

**Comment by Kulbear** [comment]
![image](https://cloud.githubusercontent.com/assets/14886380/24834747/b7c5d3f6-1d20-11e7-8c54-1eda805f2169.png)

![image](https://cloud.githubusercontent.com/assets/14886380/24834755/d65fd6cc-1d20-11e7-8459-06915594f465.png)

请下载 node 并安装。
