### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Mikey2008** [geeeeeeeeek/electronic-wechat#481]
#### Describe

when i push command+q to quit electronic-wechat, there is an error named "A JavaScript error occurred in the main process",and i push ok, another error apeared

#### Specifications

- Version of Electron (run `$ electron --version`): `electron-wechat v2.0.0`(Powered by electron 1.4.7)
- OS: `macOS 10.12.4`
- Stack trace from the error message:

```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at BrowserWindow.loadURL (/Applications/Electronic WeChat.app/Contents/Resources/electron.asar/browser/api/browser-window.js:159:16)
    at WeChatWindow.loadURL (/Applications/Electronic WeChat.app/Contents/Resources/app.asar/src/windows/controllers/wechat.js:72:23)
    at Timeout.setInterval [as _repeat] (/Applications/Electronic WeChat.app/Contents/Resources/app.asar/src/windows/controllers/wechat.js:97:14)
    at Timeout.wrapper [as _onTimeout] (timers.js:425:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```
```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at BrowserWindow.loadURL (/Applications/Electronic WeChat.app/Contents/Resources/electron.asar/browser/api/browser-window.js:159:16)
    at WeChatWindow.loadURL (/Applications/Electronic WeChat.app/Contents/Resources/app.asar/src/windows/controllers/wechat.js:72:23)
    at Timeout.setInterval [as _repeat] (/Applications/Electronic WeChat.app/Contents/Resources/app.asar/src/windows/controllers/wechat.js:97:14)
    at Timeout.wrapper [as _onTimeout] (timers.js:425:11)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
    at listOnTimeoutNT (timers.js:250:26)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by kexul** [comment]
I encountered this error but I had not done anything....It just popped out suddenly..
