### ISSUE TITLE
在Ubuntu上启动报错

### ISSUE THREAD

**Issue by kkyflying** [geeeeeeeeek/electronic-wechat#525]
您好
在Ubuntu16.04上
tmp-6482-0-electron-v1.4.15-linux-x64.zip
在master分支上的最新版本。
在编译完成后，启动会报错
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'nconf'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/home/kk/libs/electronic-wechat/dist/electronic-wechat-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kk/libs/electronic-wechat/dist/electronic-wechat-linux-x64/resources/app.asar/src/configuration.js:7:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

祝好！

**Comment by kkyflying** [comment]
@geeeeeeeeek

**Comment by eNkru** [comment]
run npm install before build. You don't have the dependencies.
