### ISSUE TITLE
mac最新dp版 下 启动出错

### ISSUE THREAD

**Issue by anuxs** [geeeeeeeeek/electronic-wechat#547]
#### Description

npm start 启动出错，信息如下

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- OS: `<OS>`
Darwin 17.0.0
- Stack trace from the error message (if any)
➜  electronic-wechat git:(master) ✗ npm start

> electronic-wechat@2.0.0 start /Users/langge/dev/test/h5js/electronic-wechat
> electron src/main.js

sh: electron: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electronic-wechat@2.0.0 start: `electron src/main.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electronic-wechat@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/langge/.npm/_logs/2017-08-17T22_57_33_153Z-debug.log
➜  electronic-wechat git:(master) ✗ 

```
<Stack trace here>
0 info it worked if it ends with ok
1 verbose cli [ '/Users/langge/.nvm/versions/node/v8.3.0/bin/node',
1 verbose cli   '/Users/langge/.nvm/versions/node/v8.3.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v8.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electronic-wechat@2.0.0~prestart: electronic-wechat@2.0.0
6 info lifecycle electronic-wechat@2.0.0~start: electronic-wechat@2.0.0
7 verbose lifecycle electronic-wechat@2.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle electronic-wechat@2.0.0~start: PATH: /Users/langge/.nvm/versions/node/v8.3.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/langge/dev/test/h5js/electronic-wechat/node_modules/.bin:/Users/langge/.nvm/versions/node/v8.3.0/bin:/Users/langge/dev/google/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:/Users/langge/.rvm/bin
9 verbose lifecycle electronic-wechat@2.0.0~start: CWD: /Users/langge/dev/test/h5js/electronic-wechat
10 silly lifecycle electronic-wechat@2.0.0~start: Args: [ '-c', 'electron src/main.js' ]
11 info lifecycle electronic-wechat@2.0.0~start: Failed to exec start script
12 verbose stack Error: electronic-wechat@2.0.0 start: `electron src/main.js`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/Users/langge/.nvm/versions/node/v8.3.0/lib/node_modules/npm/lib/utils/spawn.js:33:16)
12 verbose stack     at emitTwo (events.js:125:13)
12 verbose stack     at ChildProcess.emit (events.js:213:7)
12 verbose stack     at maybeClose (internal/child_process.js:927:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13 verbose pkgid electronic-wechat@2.0.0
14 verbose cwd /Users/langge/dev/test/h5js/electronic-wechat
15 verbose Darwin 17.0.0
16 verbose argv "/Users/langge/.nvm/versions/node/v8.3.0/bin/node" "/Users/langge/.nvm/versions/node/v8.3.0/bin/npm" "start"
17 verbose node v8.3.0
18 verbose npm  v5.3.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error electronic-wechat@2.0.0 start: `electron src/main.js`
23 error spawn ENOENT
24 error Failed at the electronic-wechat@2.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

```

**Comment by Rocket1184** [comment]
很明显，你没有 `electron` ...

运行之前 `npm install` 过了吗

**Comment by anuxs** [comment]
必然运行过了啊。。。

➜  electronic-wechat git:(master) ✗ npm install

> electron@1.4.15 postinstall /Users/langge/dev/test/h5js/electronic-wechat/node_modules/electron
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
added 6 packages in 106.788s
