### ISSUE TITLE
npm install && start error

### ISSUE THREAD

**Issue by minhao1995** [geeeeeeeeek/electronic-wechat#560]
#### Description

First of all, thanks for your attention to open an issue for this project.
Please notice that if you are requesting a **feature**, then you should give a **brief description** of your request.
If you are reporting a **bug**, please **follow the template** below.
A bug report **without detailed information** required will have a **very low priority** and even be **ignored** (closed directly)!

#### Specifications

- Version of Electron (run `$ electron --version`): electron@1.4.15
- OS: ` Ubuntu 14.04 Linux 4.4.0-93-generic`
- Stack trace from the error message (if any)

```
node install.js

/home/minhau/electronic-wechat/node_modules/electron/install.js:46
  throw err
  ^

Error: tunneling socket could not be established, cause=write EPROTO 139900242265984:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:797:

    at ClientRequest.onError (/home/minhau/electronic-wechat/node_modules/tunnel-agent/index.js:177:17)
    at ClientRequest.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:343:10)
    at onwrite (_stream_writable.js:361:5)
    at WritableState.onwrite (_stream_writable.js:90:5)
npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/usr/node/bin/node" "/usr/node/bin/npm" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.15 postinstall: `node install.js`
npm ERR! Exit status 1

```

**Comment by F12EN** [comment]
Maybe you can do it in a different way, like downloading release.(https://github.com/geeeeeeeeek/electronic-wechat/releases)

**Comment by minhao1995** [comment]
I have solved this problem,thanks. In china,downloading release is so hard,the speed is too low and terrible.And I have a suggestion ,could we upload this release to baidu cloud and  distribute the link

**Comment by wangy325** [comment]
how to solve this problem?  my  ERR repot below :
npm ERR! Linux 4.8.0-36-generic
npm ERR! argv "/opt/node-v6.11.2-linux-x64/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.15 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

**Comment by wangy325** [comment]
`shell.sh npm ERR! Linux 4.8.0-36-generic`
`npm ERR! argv "/opt/node-v6.11.2-linux-x64/bin/node" "/usr/local/bin/npm" "install"`
`npm ERR! node v6.11.2`
`npm ERR! npm  v3.10.10`
`npm ERR! code ELIFECYCLE`

`npm ERR! electron@1.4.15 postinstall: node install.js`
`npm ERR! Exit status 1`
`npm ERR! `
`npm ERR! Failed at the electron@1.4.15 postinstall script 'node install.js'.`
`npm ERR! Make sure you have the latest version of node.js and npm installed.`

> Ifyou do, this is most likely a problem with the electron package, not with npm itself.Tell the author that this fails on your system:

`npm ERR!     node install.js`

I encountered the same problem with u when I execute  `npm install && npm start`,`could u tell me how to solve it ?  
looking forward for your reply.
thanks very much!

**Comment by minhao1995** [comment]
are you in china ? if you are in china ,you can change the source to taobao
,if that doesn't make it .I can send you the software that has been
complied.

2017-09-18 13:14 GMT+08:00 wangy325 <notifications@github.com>:

**Comment by wangy325** [comment]
@minhao1995 
what do u mean by saying change the source to taobao?   do u mean change the download server to `mirrors.aliyun.com` or something else ?   The `mirrors.aliyun.com`  has been set as default server. 

it's  very kind of u to send me the released version of electroinc-wechat, the download link cannot be accessed  in mainland. my personal email is 

> wangy325@qq.com

my pc info is `Linux ubuntu 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

Thank u again.

**Comment by SunerIvy** [comment]
I met the same question. What can I do to solve this problem?
