### ISSUE TITLE
no such file or directory, open C:\Users\lenovo\AppData\Roaming\electronic-wechat\trayConfig.json

### ISSUE THREAD

**Issue by forconz** [geeeeeeeeek/electronic-wechat#599]
I download source code from link:
https://github.com/geeeeeeeeek/electronic-wechat/tree/production

PS D:\electronic-wechat> cnpm install
- [electron-localshortcut@github:parro-it/electron-localshortcut#b1119d46c0582263a7c20c1bcd710476dafcfe01] install elect
ron-localshortcut from git github:parro-it/electron-localshortcut#b1119d46c0582263a7c20c1bcd710476dafcfe01, may be very
slow, please keep patience
| [8/12] Installing rechoir@^0.6.2
D:\electronic-wechat\node_modules\_nodejieba@2.2.5@nodejieba>node "C:\Users\lenovo\AppData\Roaming\npm\node_modul
es\cnpm\node_modules\npminstall\node-gyp-bin\\node-gyp.js" rebuild
\ [9/12] Installing es6-symbol@~3.1.1在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
- [9/12] Installing es6-symbol@~3.1.1  index.cpp
  nodejieba.cpp
  win_delay_load_hook.cc
\ [9/12] Installing es6-symbol@~3.1.1d:\electronic-wechat\node_modules\_nan@2.3.5@nan\nan_maybe_43_inl.h(88): war
ning C4996: 'v8::Object::ForceSet': 被声明
为已否决 (编译源文件 ..\lib\nodejieba.cpp)d:\electronic-wechat\node_modules\_nan@2.3.5@nan\nan_maybe_43_inl.h(88)
: warning C
4996: 'v8::Object::ForceSet': 被声明为已否决 (编译源文件 ..\lib\index.cpp) [D:\electronic-wechat\node_modules\_no
dejieba@2.2.5@
nodejieba\build\nodejieba.vcxproj]

  c:\users\lenovo\.node-gyp\9.2.0\include\node\v8.h(3117): note: 参见“v8::Object::ForceSet”的声明 (编译源文件 ..\lib\n
odejieba.cp
  p)c:\users\lenovo\.node-gyp\9.2.0\include\node\v8.h(3117): note: 参见“v8::Object::ForceSet”的声明 (编译源文件 ..\lib
\index.cpp)

\ [9/12] Installing es6-symbol@~3.1.1    正在创建库 D:\electronic-wechat\node_modules\_nodejieba@2.2.5@nodejieba\
build\Release\nodejieba.lib 和对象 D:\elect
  ronic-wechat\node_modules\_nodejieba@2.2.5@nodejieba\build\Release\nodejieba.exp
  正在生成代码
/ [9/12] Installing es6-symbol@~3.1.1  已完成代码的生成
\ [9/12] Installing es6-symbol@~3.1.1  nodejieba.vcxproj -> D:\electronic-wechat\node_modules\_nodejieba@2.2.5@no
dejieba\build\Release\\nodejieba.node
√ Installed 12 packages
√ Linked 323 latest versions
√ Run 1 scripts
peerDependencies link ajv@4.11.8 in D:\electronic-wechat\node_modules\_ajv-keywords@1.5.1@ajv-keywords unmet with
 D:\electronic-wechat\node_modules\ajv(5.5.1)
Recently updated (since 2017-12-03): 2 packages (detail see file D:\electronic-wechat\node_modules\.recently_upda
tes.txt)
√ All packages installed (366 packages installed from npm registry, 1 packages installed from git, used 25s, speed 53.4
4kB/s, json 334(609.08kB), tarball 711.77kB)
PS D:\electronic-wechat> npm start

> electronic-wechat@2.0.0 start D:\electronic-wechat
> electron src/main.js

(node:4284) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

**Comment by forconz** [comment]
on top of this issue page, I enter keyword: trayConfig.json to search this file.
https://github.com/geeeeeeeeek/electronic-wechat/search?utf8=✓&q=trayConfig.json&type=

there are nothing.

**Comment by forconz** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v9.2.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electronic-wechat@2.0.0~prestart: electronic-wechat@2.0.0
6 info lifecycle electronic-wechat@2.0.0~start: electronic-wechat@2.0.0
7 verbose lifecycle electronic-wechat@2.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle electronic-wechat@2.0.0~start: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\electronic-wechat\node_modules\.bin;C:\php71\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\ProgramData\Lenovo\ReadyApps;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\MySQL\MySQL Utilities 1.6\;D:\Program Files\TortoiseSVN\bin;D:\Program Files\nodejs\;D:\Program Files\Git\cmd;C:\Users\lenovo\.dnx\bin;C:\Program Files\Java\jdk1.8.0_51\bin;C:\Program Files\Java\jdk1.8.0_51\jre\bin;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files (x86)\Git\bin;C:\Users\lenovo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Git\bin;D:\Program Files\Microsoft VS Code\bin;C:\Users\lenovo\AppData\Roaming\npm;D:\Program Files\Docker Toolbox
9 verbose lifecycle electronic-wechat@2.0.0~start: CWD: D:\electronic-wechat
10 silly lifecycle electronic-wechat@2.0.0~start: Args: [ '/d /s /c', 'electron src/main.js' ]
11 silly lifecycle electronic-wechat@2.0.0~start: Returned: code: 1  signal: null
12 info lifecycle electronic-wechat@2.0.0~start: Failed to exec start script
13 verbose stack Error: electronic-wechat@2.0.0 start: `electron src/main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at EventEmitter.emit (events.js:159:13)
13 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:159:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid electronic-wechat@2.0.0
15 verbose cwd D:\electronic-wechat
16 verbose Windows_NT 10.0.14393
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v9.2.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error electronic-wechat@2.0.0 start: `electron src/main.js`
22 error Exit status 1
23 error Failed at the electronic-wechat@2.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by forconz** [comment]
#376 #359 
我这边是windows10环境，是npm start的时候出错。

I download the electronic-wechat-master.zip from
https://github.com/geeeeeeeeek

cd D:\electronic-wechat-master\electronic-wechat-master
cnpm install
npm start

> electronic-wechat@2.0.0 start D:\Marketer\electronic-wechat
> electron src/main.js



WARNING: CommandOrControl + H is not a valid accelerator.

    at WeChatWindow.initWechatWindowShortcut (D:\Marketer\electronic-wechat\src\windows\controllers\wechat.js:179:10)
    at new WeChatWindow (D:\Marketer\electronic-wechat\src\windows\controllers\wechat.js:34:10)
    at ElectronicWeChat.createWeChatWindow (D:\Marketer\electronic-wechat\src\main.js:136:25)
    at App.app.on (D:\Marketer\electronic-wechat\src\main.js:50:12)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)


WARNING: CommandOrControl + H is not a valid accelerator.

    at BrowserWindow.wechatWindow.on (D:\Marketer\electronic-wechat\src\windows\controllers\wechat.js:164:12)
    at emitOne (events.js:101:20)
    at BrowserWindow.emit (events.js:188:7)
    at WeChatWindow.show (D:\Marketer\electronic-wechat\src\windows\controllers\wechat.js:85:23)
    at WeChatWindow.resizeWindow (D:\Marketer\electronic-wechat\src\windows\controllers\wechat.js:46:12)
    at EventEmitter.ipcMain.on (D:\Marketer\electronic-wechat\src\main.js:90:25)
    at emitTwo (events.js:106:13)

it worked just fine.
#599 can be closed.
