### ISSUE TITLE
I am running into an error during building

### ISSUE THREAD

**Issue by spacealiens** [geeeeeeeeek/electronic-wechat#611]
#### Description
I am getting this error while trying to build this.

```
elliot@warmachine ~/Downloads/electronic-wechat-master $ sudo npm install && npm start
loadDep:uuid → addNamed   ▀ ╢█████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:sanitize-filename ▌ ╢███████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> nodejieba@2.2.5 install /home/elliot/Downloads/electronic-wechat-master/node_modules/nodejieba
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.13.0-17-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/elliot/Downloads/electronic-wechat-master/node_modules/nodejieba
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:nodejieba@2.2.5 nodejieba@2.2.5 install: `node-gyp rebuild`
npm WARN install:nodejieba@2.2.5 Exit status 1
npm WARN lifecycle electron@1.4.15~postinstall: cannot run in wd %s %s (wd=%s) electron@1.4.15 node install.js /home/elliot/Downloads/electronic-wechat-master/node_modules/electron
electronic-wechat@2.0.0 /home/elliot/Downloads/electronic-wechat-master
```

#### Specifications

- Version of Electron (run `$ electron --version`):
```
elliot@warmachine ~ $ electron --version
electron: command not found
elliot@warmachine ~ $ sudo apt-get install electron
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package electron
```
- OS: `Linux Mint 18 , 32 Bit`

```
Can you kindly help? I do not read/speak Chinese. Sorry.

**Comment by spacealiens** [comment]
solution: 

`apt-get install nodejs-legacy` to get the node symlink. helped solve the problem.
