### ISSUE TITLE
Ubuntu16.04安装出错，请教各路大神

### ISSUE THREAD

**Issue by xieyabos** [geeeeeeeeek/electronic-wechat#643]
xie@ubuntu:~/Downloads/electronic-wechat% sudo npm install && npm start 

> nodejieba@2.2.5 install /home/xie/Downloads/electronic-wechat/node_modules/nodejieba
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.13.0-39-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/xie/Downloads/electronic-wechat/node_modules/nodejieba
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:nodejieba@2.2.5 nodejieba@2.2.5 install: `node-gyp rebuild`
npm WARN install:nodejieba@2.2.5 Exit status 1

> electronic-wechat@2.0.0 start /home/xie/Downloads/electronic-wechat
> electron src/main.js

/usr/bin/env: ‘node’: No such file or directory

npm ERR! Linux 4.13.0-39-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electronic-wechat@2.0.0 start: `electron src/main.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the electronic-wechat@2.0.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/xie/Downloads/electronic-wechat/npm-debug.log

**Comment by Roller44** [comment]
好像你并没有安装 Node.js。On Apr 26, 2018 10:34, 谢亚波 <notifications@github.com> wrote:xie@ubuntu:~/Downloads/electronic-wechat% sudo npm install && npm start

nodejieba@2.2.5 install /home/xie/Downloads/electronic-wechat/node_modules/nodejieba
node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: gyp failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.13.0-39-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/xie/Downloads/electronic-wechat/node_modules/nodejieba
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:nodejieba@2.2.5 nodejieba@2.2.5 install: node-gyp rebuild
npm WARN install:nodejieba@2.2.5 Exit status 1

electronic-wechat@2.0.0 start /home/xie/Downloads/electronic-wechat
electron src/main.js

/usr/bin/env: ‘node’: No such file or directory
npm ERR! Linux 4.13.0-39-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! electronic-wechat@2.0.0 start: electron src/main.js
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the electronic-wechat@2.0.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/xie/Downloads/electronic-wechat/npm-debug.log
