### ISSUE TITLE
manjaro安装报错怎么弄呢？？？

### ISSUE THREAD

**Issue by Hiddensu** [geeeeeeeeek/electronic-wechat#659]
[hidden-pc electronic-wechat]# npm install && npm start

> nodejieba@2.2.6 install /home/hidden/electronic-wechat/node_modules/nodejieba
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:80:29)
gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/which/which.js:89:16
gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /usr/lib/node_modules/node-gyp/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Linux 4.14.39-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hidden/electronic-wechat/node_modules/nodejieba
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> electron@1.4.15 postinstall /home/hidden/electronic-wechat/node_modules/electron
> node install.js

**Comment by Roller44** [comment]
It seems like you have to download and install the make first.

________________________________
发送自 Windows 10 版邮件应用

发件人: Hidden
发送时间: 2018年6月8日 16:30
收件人: geeeeeeeeek/electronic-wechat
抄送: Subscribed
主题: [geeeeeeeeek/electronic-wechat] manjaro安装报错怎么弄呢？？？ (#659)

[hidden-pc electronic-wechat]# npm install && npm start
nodejieba@2.2.6 install /home/hidden/electronic-wechat/node_modules/nodejieba
node-gyp rebuild
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack at getNotFoundError (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:13:12)
gyp ERR! stack at F (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:68:19)
gyp ERR! stack at E (/usr/lib/node_modules/node-gyp/node_modules/which/which.js:80:29)
gyp ERR! stack at /usr/lib/node_modules/node-gyp/node_modules/which/which.js:89:16
gyp ERR! stack at /usr/lib/node_modules/node-gyp/node_modules/isexe/index.js:42:5
gyp ERR! stack at /usr/lib/node_modules/node-gyp/node_modules/isexe/mode.js:8:5
gyp ERR! stack at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Linux 4.14.39-1-MANJARO
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/hidden/electronic-wechat/node_modules/nodejieba
gyp ERR! node -v v10.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
electron@1.4.15 postinstall /home/hidden/electronic-wechat/node_modules/electron
node install.js
