### ISSUE TITLE
OSX 10.11.2报错

### ISSUE THREAD

**Issue by Jasonix** [geeeeeeeeek/electronic-wechat#7]
#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v0.0.0`
- OS: `<OS>`
- Architecture `<ARCH>`
- Stack trace from the error message (if any)

``` 
➜  electronic-wechat git:(master) ✗ npm start

> electronic-wechat@0.1.0 start /Users/Jason/Code/Github/electronic-wechat
> electron src/main.js

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/Jason/Code/Github/electronic-wechat/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/Users/Jason/Code/Github/electronic-wechat/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@0.1.0 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electronic-wechat@0.1.0 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jason/Code/Github/electronic-wechat/npm-debug.log
```

**Comment by geeeeeeeeek** [comment]
@Jasonix 我错误地将node_modules推送上来了，可能是因为这个导致的path错误。你试试删除node_modules重新npm install？

**Comment by Jasonix** [comment]
多谢，问题解决了
