### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by xxxifan** [geeeeeeeeek/electronic-wechat#94]
First, make sure your issue is strictly related to the ***Electronic WeChat*** project. If it's a question or feature request, you can remove the template below.

#### Description

when I ran 'npm start', it shows:

```
npm start

> electronic-wechat@1.1.1 start /opt/application/electronic-wechat
> electron src/main.js

fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/opt/application/electronic-wechat/node_modules/electron-prebuilt/path.txt'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/opt/application/electronic-wechat/node_modules/electron-prebuilt/index.js:4:42)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)

npm ERR! Linux 4.4.5-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v5.9.0
npm ERR! npm  v3.8.2
npm ERR! code ELIFECYCLE
npm ERR! electronic-wechat@1.1.1 start: `electron src/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electronic-wechat@1.1.1 start script 'electron src/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electronic-wechat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron src/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electronic-wechat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electronic-wechat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/application/electronic-wechat/npm-debug.log
```

#### Specifications

- Version of Electron (run `$ electron --version`): `v0.0.0`
- Version of Node.js (run `$ node --version`): `v5.9.0`
- OS: `Linux 4.4.5-1-ARCH`
- Architecture `X86_64`
- Stack trace from the error message (if any)

``` 
<Stack trace here>
```

**Comment by geeeeeeeeek** [comment]
你的`electron-prebuilt`版本？我认为是electron的锅，你uninstall在`npm install`一下试试。

**Comment by xxxifan** [comment]
应该是 我是用npm install electron-prebuilt -g命令安装的electron
然后我用npm run build:linux打包的版本可以运行，但这里我有个问题，每次打开都需要扫码  是本身就是这样的还是这个打包版本的bug？

**Comment by geeeeeeeeek** [comment]
和Web端一样，每次打开都要扫码。
